### PR TITLE
readme: Update readme with instructions for proxy

### PR DESCRIPTION
**Pull request by wbnns**
This updates the readme with instructions for how to operate the proxy.

### CODE REVIEW

**Comment by skynode** [comment]
Thanks for the MD compliant formatting Will.

**Comment by wbnns** [comment]
You're welcome! Did you mean to revert the PR?

**Comment by skynode** [comment]
Hey! Oh I just thought to include some 21 install information and then move what you did to the micropayments-proxy folder since the `blockchain-dev` repo will include a bunch of other bitcoin app projects like the ones listed [here](https://21.submittable.com/submit) and possibly extensions of the current stock of tutorials, with each project having its own `README.md` file.

Based on that, the new location for the file you created is `skynode/blockchain-dev/micropayments-proxy/README.md`. What d'you think?

**Comment by wbnns** [comment]
Ah! Ok, cool, yeah, makes sense! 👍

**Pull request merged**
